### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by efedoganay** [JialeCao001/D2Det#15]
Hi, thanks for sharing your code.

Do we need to install mmdetection and put this repo under it? I followed the instructions you provided but mmdetection folder does not have any D2Det folder in configs.

**Comment by JialeCao001** [comment]
Hi. You do not need to install another mmdetection because this repo contains mmdetection. Just download this code and compile it.

**Comment by efedoganay** [comment]
Thanks, I was confused for a moment. Lastly, did you test this with CUDA 11.0 or later? I was not able to compile correctly by following the steps in the official file.

**Comment by JialeCao001** [comment]
I think that this version does not support CUDA11.0. Maybe the new provided version with mmdetection v2.1 supports it.
