### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by CuberrChen** [JialeCao001/D2Det#19]
hi！I'm trying to learn your work.but when I run the demo.py , the error happened. as you can see, the code can't perfom. 
my environmental configuration：
python=3.7
pytorch=1.4
cuda = 10.0
mmcv=0.4.3

`    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/Loops.cuh:103)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f4a9e223627 in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x78d (0x7f4aaa4fc68d in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x571bf32 (0x7f4aaa4f5f32 in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x571c298 (0x7f4aaa4f6298 in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x16957eb (0x7f4aa646f7eb in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x47e (0x7f4aa646b5ae in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x1c0155a (0x7f4aa69db55a in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x1c06023 (0x7f4aa69e0023 in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x3820d1a (0x7f4aa85fad1a in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: <unknown function> + 0x1c06023 (0x7f4aa69e0023 in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #10: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0x191 (0x7f4ad50ea931 in /home/chenxiangbo/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: nms_cuda(at::Tensor, float) + 0x84f (0x7f4a7b0e3bbc in /home/chenxiangbo/D2Det/demo/../mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #12: nms(at::Tensor const&, float) + 0xee (0x7f4a7b0d217e in /home/chenxiangbo/D2Det/demo/../mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #13: <unknown function> + 0x3c75b (0x7f4a7b0e175b in /home/chenxiangbo/D2Det/demo/../mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x38ee0 (0x7f4a7b0ddee0 in /home/chenxiangbo/D2Det/demo/../mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
`

**Comment by JialeCao001** [comment]
@FireflyInwater Hi. Thanks for interest. Please to use pytorch1.1.0.
