### ISSUE TITLE
Question about Discriminative RoI Pooling

### ISSUE THREAD

**Issue by cookchicken** [JialeCao001/D2Det#25]
Firstly, thank you for such a greate work. But I have a little problem when I reading your code. In the paper I know that the Discriminative RoI pooling create the Weighted RoI feature with F~ =W(F)⊙ F. But In your code the Weighted RoI feature is created by `return F.avg_pool2d(x * weight, kernel, stride, padding) / F.avg_pool2d(weight, kernel, stride, padding)`.
I don't know why do it divide by `F.avg_pool2d(weight, kernel, stride, padding)`

**Comment by JialeCao001** [comment]
@cookchicken Thanks for your interest. It is used for normalization.

**Comment by cookchicken** [comment]
> @cookchicken Thanks for your interest. It is used for normalization.



> @cookchicken Thanks for your interest. It is used for normalization.
