### ISSUE TITLE
iSAID weights

### ISSUE THREAD

**Issue by trungpham2606** [JialeCao001/D2Det#3]
@JialeCao001 
Thank you for sharing such a great work!
I have seen on your paper that you guys also made a comparison on iSAID dataset. Can you please public the weights you had trained on that dataset ?
Thanks in advance

**Comment by JialeCao001** [comment]
Hi, thinks for your interests. Currently, we do not plan to prepare the weights for iSAID.

**Comment by Elaineok** [comment]
@JialeCao001
Hi,Thank you for sharing such a great work!
Did you provide the code for the  iSAID instance segmentation in this project？
Thank you for your reply
