### ISSUE TITLE
Compatibility with latest "mmdetection"

### ISSUE THREAD

**Issue by vguptai** [JialeCao001/D2Det#9]
Hi @JialeCao001,

Thanks for sharing this amazing work. 

I have a question regarding the installation steps. Do we need to pull and build the latest code from "https://github.com/open-mmlab/mmdetection" or would it be sufficient to build the "mmdet" folder present within this repository. 

I noticed that there are some latest changes in the "mmdetection" repository which are not compatible with D2Det. 

Thanks

**Comment by JialeCao001** [comment]
The compatibility between mmdetection1.x and mmdetection2.x seems not very good. You can use the mmdetection version in this project.

**Comment by JialeCao001** [comment]
If you want to use the lastest version of mmdetection, I think it is easy to put the module in that version by yourself.

**Comment by vguptai** [comment]
Thanks @JialeCao001 , I am able to run the project by compiling the mmdetection version present in this project. It would be helpful to update this information in the installation steps also.
